/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as BracketRouteImport } from './routes/bracket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCalendarRouteImport } from './routes/api/public/calendar'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketRoute = BracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarRoute = ApiPublicCalendarRouteImport.update({
  id: '/api/public/calendar',
  path: '/api/public/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predict': typeof PredictRoute
  '/results': typeof ResultsRoute
  '/api/public/calendar': typeof ApiPublicCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predict': typeof PredictRoute
  '/results': typeof ResultsRoute
  '/api/public/calendar': typeof ApiPublicCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predict': typeof PredictRoute
  '/results': typeof ResultsRoute
  '/api/public/calendar': typeof ApiPublicCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bracket'
    | '/leaderboard'
    | '/predict'
    | '/results'
    | '/api/public/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bracket'
    | '/leaderboard'
    | '/predict'
    | '/results'
    | '/api/public/calendar'
  id:
    | '__root__'
    | '/'
    | '/bracket'
    | '/leaderboard'
    | '/predict'
    | '/results'
    | '/api/public/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BracketRoute: typeof BracketRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PredictRoute: typeof PredictRoute
  ResultsRoute: typeof ResultsRoute
  ApiPublicCalendarRoute: typeof ApiPublicCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket': {
      id: '/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof BracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar': {
      id: '/api/public/calendar'
      path: '/api/public/calendar'
      fullPath: '/api/public/calendar'
      preLoaderRoute: typeof ApiPublicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BracketRoute: BracketRoute,
  LeaderboardRoute: LeaderboardRoute,
  PredictRoute: PredictRoute,
  ResultsRoute: ResultsRoute,
  ApiPublicCalendarRoute: ApiPublicCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
